version: "3.4"

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "RkPs090320"
      POSTGRES_DB: "tinyurl_db"

  backend:
    depends_on:
      - database
    build: ./tinyurl_backend
    ports:
      - "8000:8000"

  frontend:
    depends_on:
      - database
      - backend
    build: ./tinyurl_frontend
    ports:
      - "3000:3000"
