version: "3.4"

services:
  tinyurl_backend:
    build: ./tinyurl_backend
    environment:
      PORT: 8000
    env_file:
      - .env
    ports:
      - 8000:8000

  tinyurl_frontend:
    build: ./tinyurl_frontend
    environment:
      PORT: 3000
    ports:
      - 3000:3000